# ===============================
# 🏦 APPLICATION
# ===============================
spring.application.name=BANK-USER-SERVICE
server.port=8082

# ===============================
# 🗄️ DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/bank_user_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# ⚙️ JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 🌐 EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# 📘 SWAGGER
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# 🔁 GATEWAY HEADERS
# ===============================
server.forward-headers-strategy=framework

# ===============================
# 📝 LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.bank.user=DEBUG

logging.file.name=logs/user-service.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n